# Generated by Django 4.2.4 on 2024-03-16 17:58

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='mail',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='picture',
            field=models.ImageField(upload_to=client.models.prospect_pic),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='telephone',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
