# Generated by Django 5.0 on 2024-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_prospect_date_alter_prospect_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='sex',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
