# Generated by Django 5.0 on 2024-03-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_prospect_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='frequency',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
