# Generated by Django 5.0 on 2024-03-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_prospect_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='telephone',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
